# Generated by Django 5.0.1 on 2024-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_submission_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='source_lang',
            field=models.CharField(choices=[('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name'), ('id', 'name')], max_length=2),
        ),
        migrations.AlterField(
            model_name='submission',
            name='token',
            field=models.JSONField(),
        ),
    ]
