# Generated by Django 5.0.1 on 2024-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
