# Generated by Django 5.0.1 on 2024-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_problem_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='train_cases',
        ),
        migrations.AddField(
            model_name='problem',
            name='cases',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
