# Generated by Django 5.0.4 on 2024-04-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_problem_test_cases_remove_problem_train_cases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='source_lang',
            field=models.IntegerField(),
        ),
    ]
